/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package golem;

import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.GraphicsConfiguration;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.UUID;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.vecmath.Vector3f;
/**
 *
 * @author evergaster
 */
public class golem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(golem.class.getName());
    crearEscenaGrafica creaEscena;
    HiloCaminar hcCaminar;
    HiloBaile hcBaile;
    boolean bandera = false;
    boolean bailando = false;



    private String usuarioLogueado;
    private UUID idUsuario;
    private javax.swing.JPanel panelPuntajes;
    private javax.swing.JLabel lblPuntajes;
    private javax.swing.JLabel lblEstado;
    private java.util.Timer timerActualizarPosiciones;
    private int victoriasJugador = 0;
    private int victoriasOponente = 0;
    private int rondaActual = 1;
    private boolean juegoTerminado = false;

    public golem(String username, UUID id) {
        this.usuarioLogueado = username;
        this.idUsuario = id;
        initComponents();
        GraphicsConfiguration config = SimpleUniverse.getPreferredConfiguration();
        Canvas3D lienzo = new Canvas3D(config);
        lienzo.setBounds(0, 50, 700, 550); // Ajustar para ocupar el espacio debajo del panel
        this.add(lienzo, java.awt.BorderLayout.CENTER);
        this.setBounds(300, 50, 700, 600);
        BranchGroup Scene = new BranchGroup();
        creaEscena = new crearEscenaGrafica();
        Scene = creaEscena.bgRaiz;
        SimpleUniverse n = new SimpleUniverse(lienzo);
        n.getViewingPlatform().setNominalViewingTransform();
        n.addBranchGraph(Scene);
        hcCaminar = new HiloCaminar(creaEscena);
        configurarControlesTeclado();
        iniciarTimerPosiciones();
    }

    private void configurarControlesTeclado() {
        JComponent root = (JComponent) this.getContentPane();
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_UP, 0), "moverArriba");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_DOWN, 0), "moverAbajo");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_LEFT, 0), "moverIzquierda");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_RIGHT, 0), "moverDerecha");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_W, 0), "moverArriba");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_S, 0), "moverAbajo");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_A, 0), "moverIzquierda");
        root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_D, 0), "moverDerecha");

        root.getActionMap().put("moverArriba", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creaEscena.caminar();
                checkWin();
            }
        });

        root.getActionMap().put("moverAbajo", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creaEscena.moverTorso(8, 0.0f, 0.0f, -0.05f);
                creaEscena.caminar();
                checkWin();
            }
        });

        root.getActionMap().put("moverIzquierda", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creaEscena.moverTorso(8, -0.05f, 0.0f, 0.0f);
                creaEscena.caminar();
                checkWin();
            }
        });

        root.getActionMap().put("moverDerecha", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creaEscena.moverTorso(8, 0.05f, 0.0f, 0.0f);
                creaEscena.caminar();
                checkWin();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPuntajes = new javax.swing.JPanel();
        lblPuntajes = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arena Golem - " + usuarioLogueado);

        panelPuntajes.setBackground(new java.awt.Color(0, 0, 0));
        panelPuntajes.setPreferredSize(new java.awt.Dimension(700, 50));

        lblPuntajes.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntajes.setText("Puntajes: Tú 0 - Oponente 0 | Ronda 1");

        lblEstado.setForeground(new java.awt.Color(255, 255, 0));
        lblEstado.setText("Esperando inicio...");

        javax.swing.GroupLayout panelPuntajesLayout = new javax.swing.GroupLayout(panelPuntajes);
        panelPuntajes.setLayout(panelPuntajesLayout);
        panelPuntajesLayout.setHorizontalGroup(
            panelPuntajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPuntajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addContainerGap())
        );
        panelPuntajesLayout.setVerticalGroup(
            panelPuntajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntajes)
                    .addComponent(lblEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPuntajes, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPuntajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        // ... (el código del Look and Feel Nimbus que ya tienes)

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Creamos un ID temporal y un nombre por si corres este archivo solo
            UUID idTemporal = UUID.randomUUID();
            new golem("Invitado", idTemporal).setVisible(true);
        });
    }

    private void iniciarTimerPosiciones() {
        timerActualizarPosiciones = new java.util.Timer();
        timerActualizarPosiciones.scheduleAtFixedRate(new java.util.TimerTask() {
            @Override
            public void run() {
                actualizarPosicionEnDB();
                leerPosicionesOtrosJugadores();
            }
        }, 0, 100); // Cada 100ms
    }

    private void actualizarPosicionEnDB() {
        // Obtener posición actual del golem
        // Por ahora, simular
        // Enviar a DB posiciones_golem
    }

    private void leerPosicionesOtrosJugadores() {
        // Leer de DB posiciones_golem y actualizar otros golems
    }

    private void checkWin() {
        Vector3f pos = creaEscena.getPosicionTorso();
        if (pos.length() < 0.2) { // close to center
            victoriasJugador++;
            rondaActual++;
            lblPuntajes.setText("Puntajes: Tú " + victoriasJugador + " - Oponente " + victoriasOponente + " | Ronda " + rondaActual);
            lblEstado.setText("¡Ganaste la ronda!");
            if (rondaActual > 3) {
                juegoTerminado = true;
                mostrarFinJuego();
            } else {
                reiniciarRonda();
            }
        }
    }

    private void reiniciarRonda() {
        // Reset position
        creaEscena.moverTorso(8, 0.0f, 0.0f, 0.0f);
        lblEstado.setText("Ronda " + rondaActual + " comenzando...");
    }

    private void mostrarFinJuego() {
        lblEstado.setText("Juego terminado. Ganador: " + (victoriasJugador > victoriasOponente ? "Tú" : "Oponente"));
        // Add buttons for exit or lobby
        javax.swing.JButton btnSalir = new javax.swing.JButton("Salir");
        javax.swing.JButton btnLobby = new javax.swing.JButton("Regresar al Lobby");
        panelPuntajes.add(btnSalir);
        panelPuntajes.add(btnLobby);
        btnSalir.addActionListener(e -> System.exit(0));
        btnLobby.addActionListener(e -> {
            this.dispose();
            new LobbyFrame(usuarioLogueado, idUsuario).setVisible(true);
        });
        panelPuntajes.revalidate();
        panelPuntajes.repaint();
    }
}
